swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
tags:
  - name: User Module
  - name: Transaction Module
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
/{account}/transactions:
   get:
    security:
        - Bearer: []
   tags:
        - Transaction Module
summary: User search Transactions API
description: API for fetching list of transactions for the current month
parameters:
  - in: header
    name: Authorization
    description: Attach Bearer JWT token
    required: true
produces:
        - application/json
responses:
        '200':
          description: list of transactions for the current month retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
/{account}/transactions/{id}:
get:
    security:
        - Bearer: []
    tags:
        - Transaction Module
    summary: User search TransactionbyID API
    description: API for fetching one transaction for the current month with its ID
    parameters:
        - in: query
          type: string
          name: id
          description: find one transaction by id
          required: true
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
    produces:
        - application/json
    responses:
        '200':
          description: transaction by id retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: transaction not found
        '500':
          description: Internal Server Error
/{account}/transactions/{id}/addInformations:
post:
    security:
        - Bearer: []
    tags:
        - Transaction Module
    summary: User search TransactionbyID API and add some informations
    description: API for fetching one transaction for the current month with its ID and add some informations
    parameters:
        - in: query
          type: string
          name: id
          description: find one transaction by id and add some informations
          required: true
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Add some informations to transactions attributes
          required: true  
    produces:
        - application/json
    responses:
        '200':
          description: Add some information to transaction by id retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: unable to add information
        '500':
          description: Internal Server Error  
/{account}/transactions/{id}/UpdateInformations:
put:
    security:
        - Bearer: []
    tags:
        - Transaction Module
    summary: User search TransactionbyID API and update some informations
    description: API for fetching one transaction for the current month with its ID and update some informations
    parameters:
        - in: query
          type: string
          name: id
          description: find one transaction by id and update some informations
          required: true
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update some informations to transactions attributes
          required: true    
    produces:
        - application/json
    responses:
        '200':
          description: Upadte some information to transaction by id retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: unable to update information
        '500':
          description: Internal Server Error
/{account}/transactions/{id}/DeleteInformations:
delete:
    security:
        - Bearer: []
    tags:
        - Transaction Module
    summary: User search TransactionbyID API and delete some informations
    description: API for fetching one transaction for the current month with its ID and delete some informations
    parameters:
        - in: query
          type: string
          name: id
          description: find one transaction by id and delete some informations
          required: true
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
    produces:
        - application/json
    responses:
        '200':
          description: Delete some information to transaction by id retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: unable to delete information
        '500':
          description: Internal Server Error            
          
          
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string

